name: Deploy to Staging

on:
  push:
    branches: ["main"]

env:
  APP_ENV: ${{ secrets.STAGING }}
  STATUS: "❌"

jobs:
  clear-docker-cache:
    name: "Clear Docker Cache"
    runs-on: [self-hosted, staging]
    steps:
      - name: Docker Prune
        run: sudo docker system prune -f -a --volumes

  build:
    needs: [clear-docker-cache]
    name: "Deploy to Staging"
    environment:
      name: staging

    runs-on: [self-hosted, staging]

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }} for pull code (CD)
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Delete old env file
        run: rm -r -f .env

      - name: Create env_temp file
        run: touch .env_temp

      - name: Copy Secret Key Multiline environment variable to .env_temp file
        run: echo $APP_ENV | tee .env_temp

      - name: Replace space character with break-line in .env file
        run: sed 's/ /\n/g' .env_temp >> .env

      - name: Remove .env_temp file
        run: rm -r -f .env_temp

      - name: Build Docker and deployment
        run: sudo chmod +x docker-build.sh && sudo ./docker-build.sh

      - name: Set build status emoji to success
        run: echo "STATUS=✅" >> $GITHUB_ENV

      - name: Post build result to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: "C053JVDGG12"
          payload: |
            {
              "text": "TODO-LIST-WEBSITE-FE-STAGE ${{ env.STATUS }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<https://github.com/abc-software-solutions-company/todo-list-website/actions/runs/${{ github.run_id }}|TODO-LIST-WEBSITE-*FE-STAGE* ${{ env.STATUS }}>"
                  }
                }
              ]
            }

        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        if: always()
