name: Deploy to Production

on:
  push:
    branches: ["release"]

env:
  APP_ENV: ${{ secrets.PRODUCTION }}
  STATUS: "âŒ"

jobs:
  build:
    name: "Deploy to Production"
    environment:
      name: production

    runs-on: [self-hosted, production]

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }} for pull code (CD)
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Delete old env file
        run: rm -r -f .env

      - name: Create env_temp file
        run: touch .env_temp

      - name: Copy Secret Key Multiline environment variable to .env_temp file
        run: echo $APP_ENV | tee .env_temp

      - name: Replace space character with break-line in .env file
        run: sed 's/ /\n/g' .env_temp >> .env

      - name: Set Github Commit SHA ID
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Append Github Commit SHA ID to .env file
        run: echo NEXT_PUBLIC_GIT_COMMIT_SHA=${{ steps.vars.outputs.sha_short }} >> .env

      - name: Remove .env_temp file
        run: rm -r -f .env_temp

      - name: Build Docker and deployment
        run: sudo chmod +x docker-build.sh && sudo ./docker-build.sh

      - name: Prune docker image trash
        run: sudo docker rmi -f $(sudo docker images --filter "dangling=true" -q --no-trunc)
        if: always()

      - name: Prune docker container trash
        run: sudo docker container prune -f --filter "until=24h"
        if: always()

      - name: Post build result to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: "C053JVDGG12"
          payload: |
            {
              "text": "TODO-LIST-WEBSITE-FE-PRODUCTION ${{ env.STATUS }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<https://github.com/abc-software-solutions-company/todo-list-website/actions/runs/${{ github.run_id }}|TODO-LIST-WEBSITE-*FE-PRODUCTION* ${{ env.STATUS }}>"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        if: always()
